######################################################################
# Automatically generated by qmake (2.01a) Tue Jun 26 15:57:38 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += camera.h tabconvert.h videowidget.h cameraattr.h
FORMS += cameraattr.ui
SOURCES += camera.cpp main.cpp tabconvert.cpp videowidget.cpp cameraattr.cpp
